### ISSUE TITLE
Print Labels has character code bug with pdf

### ISSUE THREAD

**Issue by pggdt** [sivann/itdb#12]
When I use Print Labels, the characters in Chinese will be displayed as 口口 in the pdf. The Chinese characters displayed correctly in other pages.

**Comment by sivann** [comment]
Thank you for the report.
I updated tcpdf library, and added support to specify custom font for PDF labels in conf.php. At least 2 fonts with Chinese characters will be included. You can pull the latest release, or wait for a tag.
