### ISSUE TITLE
Itdb is not working on windows

### ISSUE THREAD

**Issue by skyalert** [sivann/itdb#28]
I have downloaded latest version of this software and i have try to install it on my local server for checking but i,m getting this error again and again.I have uploaded it on live server too but i,m getting same error when i tried to change itdb directory folder permissions 755 to 777 i,m getting internal server error.pLease tell me what should i do?
THanks
/home/lolololo/public_html/itdb-1.14 is not writeable by apache
make /home/lolololo/public_html/itdb-1.14/data/files/ writeable by the user running the web server
in unix:
chown  /home/lolololo/public_html/itdb-1.14/data/files/; chmod u+w /home/lolololo/public_html/itdb-1.14/data/files/

**Comment by DanielNemanic** [comment]
Is the folder "data/files/" present?

If not, create it on your own. That worked for me.

**Comment by skyalert** [comment]
Yep already here but still same problem.On local server where we can set
permissions?

On Mon, Apr 13, 2015 at 6:26 PM, Daniel Nemanic <notifications@github.com>
wrote:

> Is the folder "data/files/" present?
>
> If not, create it on your own. That worked for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sivann/itdb/issues/28#issuecomment-92350780>.
>



-- 
Web developer Designer & SEO expert
<https://www.odesk.com/users/~01a294772dad47f073>
Skype :  Sanwal.g3

**Comment by DanielNemanic** [comment]
Your Apache is running with an user account?
Check your Permission settings and give this user full access on the data folder.

Have you IIS or still Apache?

**Comment by skyalert** [comment]
yep running with user account(Apache)

**Comment by DanielNemanic** [comment]
Have you checked your virtual host file?
Or permission in httpd.conf?

	<Directory "path to your main itdb folder"> 
		AllowOverride All
		Require all granted
	</Directory>

I use IIS and everything works fine

**Comment by skyalert** [comment]
no i didn,t check :( where is it located ?

On Mon, Apr 13, 2015 at 7:22 PM, Daniel Nemanic <notifications@github.com>
wrote:

> Have you checked your virtual host file?
> Or permission in httpd.conf?
>
> <Directory "path to your main itdb folder">
>     AllowOverride All
>     Require all granted
> </Directory>
>
> I use IIS and everything works fine
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sivann/itdb/issues/28#issuecomment-92374540>.
>



-- 
Web developer Designer & SEO expert
<https://www.odesk.com/users/~01a294772dad47f073>
Skype :  Sanwal.g3

**Comment by DanielNemanic** [comment]
You have a clean Apache installation?
No virtual hosts?

You find the file under: conf

**Comment by sivann** [comment]
Hi,
I don't believe itdb can run on windows correctly.
