### ISSUE TITLE
Small bug in editsoftware.php affecting the type column's formatting in item association 

### ISSUE THREAD

**Issue by Longshot123** [sivann/itdb#35]
There is a small bug in editsoftware.php that is messing up the formatting of the editsoftware->item association 'type' column that makes the column basically unreadable. Removing $attr from line 479 fixes the problem. 

Before:
![image](https://cloud.githubusercontent.com/assets/7998003/8733450/7d3e8b96-2bc9-11e5-9209-ddaabbb14e12.png)

After:
![image](https://cloud.githubusercontent.com/assets/7998003/8733392/4b4bc914-2bc9-11e5-9b19-4312fc342a1b.png)

**Comment by sivann** [comment]
thanks, fixed.
