### ISSUE TITLE
Issue with ext4 and sqlite

### ISSUE THREAD

**Issue by Kolesar** [sivann/itdb#36]
SQLite is very slow on ext4, so please add follow line for speed up:

``$dbh->exec("pragma synchronous = off;");``

**Comment by sivann** [comment]
If you turn it off data will not be saved to disk when you click save, but asynchronously, at a later time chosen by the OS. This can be very unsafe. Why do you say it is slow, it is fast enough in my experience. Perhaps your disk is very loaded, use "iostat -xm 2" or iotop to see which process is slowing down your drive.
