### ISSUE TITLE
Edit Item: Can't add "Items Associations" after using order by in the "Inter-Item Association" table

### ISSUE THREAD

**Issue by Entropede** [sivann/itdb#43]
In edit item:
When I go in "Inter-Item Association"
And I click on "ID" to order by item by "ID"
And I click on check one or some items
And I click on "Save"

No Insert is done in "Inter-Item Associations" table
No variable Itlnk is send by the browser
The sorttable javascript code broke the form inputs for Items Association.

I use Chrome (47.0.2526.80)

The filter work #1. May-be temporary disabling the sort function can be better?

Tanks
And Nice work for ITDB!

**Comment by sivann** [comment]
Please state linux distribution, ITDB version, PHP version, SQLite PDO version. You may find those by clicking on the blue (i) icon on the left bar.

**Comment by Entropede** [comment]
Oh Sorry!

PHP version: 5.6.16
OS: FreeBSD 10.2-RELEASE-p9
PDO_SQLITE version:3.9.2
ITDB Version 1.22

**Comment by sivann** [comment]
Is there anything logged on apache's error.log while the problem occurs?

**Comment by Entropede** [comment]
Nothing in apache log

With the developpement tools of Chrome, normaly I have the variable itlnk[] in post data,
But i dont see this variable after using the sort column function, even if I try to link items.

**Comment by sivann** [comment]
you are right, I reproduce on all association pages. I cannot resolve this, I will disable sorting on those tabs for now.

**Comment by sivann** [comment]
diabled sorting, filtering works.
