### ISSUE TITLE
Multi field search not working after 1.23 upgrade 

### ISSUE THREAD

**Issue by jetstream44** [sivann/itdb#46]
Since upgrading to V1.23 the multi-field search (image attached) for "Items" no longer works. This is the function accessed by clicking the small clear elliptical looking icon at the top left of the Items list.

All the field tags are now just "Name" where they used to be "Serial Number", "Model" etc. Entering any data into the fields produces the following error when viewing the source in IE

SCRIPT5007: Unable to set property 'sSearch' of undefined or null reference. jquery.dataTables.min.js (123,196)

System details are as follows:
RHEL 6
Apache 2.2.15
PHP 5.3.3
SQLite 3.6.20

Thanks!

![itdb](https://cloud.githubusercontent.com/assets/18200549/14194575/acdc348a-f7fb-11e5-9c4d-823c03cc9df8.JPG)

**Comment by sivann** [comment]
Sorry, I cannot reproduce. Could you check your apache error.log for any entries when you open this page? Could you also open the browser console (F12) and check for any errors logged at the console window?

**Comment by jetstream44** [comment]
The following error is generated in the browser if I enter any information into the item search fields:

SCRIPT5007: Unable to set property 'sSearch' of undefined or null reference
jquery.dataTables.min.js (123,196)

Nothing is evident in the apache error log

Thanks!

**Comment by nikband** [comment]
Yes i resolve put short_open_tag = On on /etc/php.ini and apache restart... i check the code is the same of 1.22. I migrate from 1.12 (modifided by me for Admin user bug) and after the apache restart all start work correcty. I also update mod_wsgi but this not solve.

**Comment by nikband** [comment]
Sivann it's possible to add in this filter list the Note fields? Can you help me?

**Comment by sivann** [comment]
Thanks, I reproduced. I will release a fix.

**Comment by sivann** [comment]
You can download the latest commit, 9e0d6a0 which works with short_open_tag off. The default is On and will be for all future PHP versions, so I suggest you set  "short_open_tags = On" in your php.ini and then restart apache (service httpd restart) on RHEL.

To locate your php.ini, click the blue (i) on the bottom left of ITDB and search for the php.ini somewhere at the top under "Loaded Configuration File".
