### ISSUE TITLE
itdb 1.23 - Cross-Site Scripting (XSS)

### ISSUE THREAD

**Issue by bestshow** [sivann/itdb#56]
[Uploading itdb 1.23 - Cross-Site Scripting (XSS).docx…]()

**Comment by Chefkeks** [comment]
@bestshow 
> Uploading itdb 1.23 - Cross-Site Scripting (XSS).docx…

Looks like you saved too soon, so you should re-upload the document maybe ;)

**Comment by nikband** [comment]
I think that it's a possibile "spam" with virus ...

**Comment by Chefkeks** [comment]
Yes I know, that's possible too, but since @bestshow opened an issue [**here**](https://github.com/bigtreecms/BigTree-CMS/issues/264) with a valid word document too, I don't think so.

**Comment by nikband** [comment]
I hope so in a good document from @bestshow. Please bestshow attach a new document

**Comment by bestshow** [comment]
OK，I re-upload the document again.
[itdb 1.23 - Cross-Site Scripting (XSS).docx](https://github.com/sivann/itdb/files/655421/itdb.1.23.-.Cross-Site.Scripting.XSS.docx)

**Comment by bestshow** [comment]
@nikband @Chefkeks Do you see the document ?

**Comment by Chefkeks** [comment]
Everything is fine now and document can be read.
Now its up to @sivann as developer to react.

**Comment by bestshow** [comment]
Thanks.

**Comment by bestshow** [comment]
@nikband @Chefkeks Please assign CVEs if you think they are suitable for identifiers.

**Comment by sivann** [comment]
Guys pleas read the "Security" and "Welcomed pull requests" paragraphs. ITDB is full of security issues, don't expose as is on public internet. There is no patching this, it needs to be rewritten.
