### ISSUE TITLE
SQL Vulnerability

### ISSUE THREAD

**Issue by tanaydin** [sivann/itdb#61]
With SQLMap, I found that this software has problem (maybe more)

```
---
Parameter: id (GET)
    Type: boolean-based blind
    Title: OR boolean-based blind - WHERE or HAVING clause (NOT)
    Payload: action=edititem&id=5) OR NOT 1460=1460-- CDNM
    Vector: OR NOT [INFERENCE]
---
```

**Comment by attritionorg** [comment]
What script was that found in?

**Comment by tanaydin** [comment]
It is SQLMap, http://sqlmap.org/

**Comment by Entropede** [comment]
As already mentioned by @sivann , this software is an internal tool that should not be exposed publicly. Efforts to secure the software are not a priority.

See reply:
https://github.com/sivann/itdb/issues/59#issuecomment-269898929

**Comment by tanaydin** [comment]
Ok, thanks for explanation.
