### ISSUE TITLE
Full Backup probleme

### ISSUE THREAD

**Issue by so9rat** [sivann/itdb#72]
First i wanna Thx all for all hardworks and effort spend for developing this application.

i got an issue whit Full Backup it work by generate the tar.gz file but when i wanna extract the file it show me that's an unknow format or damaged and cannot use it 
Any 1 have the same probleme or can help me 

Note:
i used 3 differents application to extract the .tar.gz file 7zip, Winrar, Winzip.

**Comment by Entropede** [comment]
Same thing.  Unable to open .tar.gz file with 7zip.

ITDB Version 1.23
PDO::ATTR_CLIENT_VERSION: 3.13.0
PDO::ATTR_SERVER_VERSION: 3.13.0

Current PHP version: 5.6.23
PDO_SQLITE version:3.13.0

**Comment by sivann** [comment]
This is a linux aplication, I'm sorry but I am not familiar with winrar or
winzip and I don't have an easy access to a windows OS. 7zip should work as
far as I know.
Kind Regards,
-Spiros

**Comment by Entropede** [comment]
I found explanation of this issue for my part.  My root idtb folder isn't named "itdb", but in gettar.php I can see the compression is done on the folder "../itdb".
`passthru( "tar czf - ../itdb");`

When I change "itdb" on this line for the name of my folder, it works perfectly.

There is some reason why the path "./" isn't used in this command?
-Meaty

**Comment by sivann** [comment]
Because that wouldn't include the itdb/data, only the folder of gettar.php.

Kind Regards,
-S

**Comment by Entropede** [comment]
Sorry I dont understant.  gettar.php file is in the root directory of itdb, if "./" is zipper all files of the entire "itdb" folder will be archived.

In my case, when i use "passthru( "tar czf - ../itdb");" or "passthru( "tar czf - ./");", I have the same result (it's working).

Thanks!

**Comment by sivann** [comment]
When you extract the tar, the itdb/ folder won't be included in the 2nd case.

**Comment by Entropede** [comment]
So, a clean solution is:
`passthru( "tar czf - ../".basename(dirname(__FILE__)));`
